
server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://172.21.127.81:3306/pmt?useUnicode=true&characterEncoding=utf8
        username: root
        password: camelot!123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      
    mail:
      host: smtp.163.com
      port: 465
      username: m15043775855@163.com
      password: ao123456
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
            ssl:
              enable: true
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.camelot.pmt
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql





